x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  geth:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TAG=${GETH_BUILD_TAG}
    user: "10000"
    stop_grace_period: 1m
    image: bsc-geth:local
    pull_policy: never
    volumes:
      - geth-data:/home/bsc/data
      - ${ANCIENT_DIR:-.nada}:/home/bsc/ancient
    ports:
      - ${P2P_PORT}:${P2P_PORT}/tcp
      - ${P2P_PORT}:${P2P_PORT}/udp
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SNAPSHOT=${SNAPSHOT:-}
      - EXTRA_STATIC_NODES=${EXTRA_STATIC_NODES:-}
      - ANCIENT_DIR=${ANCIENT_DIR}
      - NETWORK=${NETWORK}
      - EXTRAS=${EXTRAS:-}
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - geth
      - --config
      - /home/bsc/config.toml
      - --datadir
      - /home/bsc/data
      - --cache
      - "8000"
      - --port
      - ${P2P_PORT:-30311}
      - --metrics
      - --metrics.addr
      - 0.0.0.0
      - --metrics.port
      - "6060"
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.port
      - ${RPC_PORT:-8545}
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${WS_PORT:-8546}
      - --ws.api
      - web3,eth,net
      - --history.transactions
      - "0"
      - --maxpeers
      - ${MAX_PEERS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.bsc.service=bsc
      - traefik.http.routers.bsc.entrypoints=websecure
      - traefik.http.routers.bsc.rule=Host(`${RPC_HOST}.${DOMAIN}`)
      - traefik.http.routers.bsc.tls.certresolver=letsencrypt
      - traefik.http.routers.bsclb.service=bsc
      - traefik.http.routers.bsclb.entrypoints=websecure
      - traefik.http.routers.bsclb.rule=Host(`${RPC_LB}.${DOMAIN}`)
      - traefik.http.routers.bsclb.tls.certresolver=letsencrypt
      - traefik.http.services.bsc.loadbalancer.server.port=${RPC_PORT}
      - traefik.http.routers.bscws.service=bscws
      - traefik.http.routers.bscws.entrypoints=websecure
      - traefik.http.routers.bscws.rule=Host(`${WS_HOST}.${DOMAIN}`)
      - traefik.http.routers.bscws.tls.certresolver=letsencrypt
      - traefik.http.routers.bscwslb.service=bscws
      - traefik.http.routers.bscwslb.entrypoints=websecure
      - traefik.http.routers.bscwslb.rule=Host(`${WS_LB}.${DOMAIN}`)
      - traefik.http.routers.bscwslb.tls.certresolver=letsencrypt
      - traefik.http.services.bscws.loadbalancer.server.port=${WS_PORT}
      - metrics.scrape=true
      - metrics.path=/debug/metrics/prometheus
      - metrics.port=6060
      - metrics.network=bsc-${NETWORK}

  set-prune-marker:
    profiles: ["tools"]
    image: alpine:3
    user: "10000:10000"
    restart: "no"
    volumes:
      - geth-data:/home/bsc/data
    entrypoint: ["/bin/sh","-c"]
    command: /bin/sh

volumes:
  geth-data:
