version: "3.9"
services:
  geth:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TARGET=${GETH_BUILD_TARGET}
    user: "10000"
    stop_grace_period: 1m
    image: bsc-geth:local
    volumes:
      - geth-data:/home/bsc/data
    ports:
      - 30311:30311/tcp
      - 30311:30311/udp
    entrypoint:
      - docker-entrypoint.sh
      - geth
      - --config
      - /home/bsc/config.toml
      - --datadir
      - /home/bsc/data
      - --cache
      - "8000"
      - --metrics
      - --metrics.addr
      - 0.0.0.0
      - --metrics.port
      - "6060"
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.port
      - ${RPC_PORT:-8545}
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${WS_PORT:-8546}
      - --ws.api
      - web3,eth,net
      - --rpc.allow-unprotected-txs
      - --txlookuplimit
      - "0"
      - --diffsync
      - --ipcdisable
    labels:
      - traefik.enable=true
      - traefik.http.routers.bsc.service=bsc
      - traefik.http.routers.bsc.entrypoints=websecure
      - traefik.http.routers.bsc.rule=Host(`${RPC_HOST}.${DOMAIN}`)
      - traefik.http.routers.bsc.tls.certresolver=letsencrypt
      - traefik.http.routers.bsclb.service=bsc
      - traefik.http.routers.bsclb.entrypoints=websecure
      - traefik.http.routers.bsclb.rule=Host(`${RPC_LB}.${DOMAIN}`)
      - traefik.http.routers.bsclb.tls.certresolver=letsencrypt
      - traefik.http.services.bsc.loadbalancer.server.port=${RPC_PORT}
      - traefik.http.routers.bscws.service=bscws
      - traefik.http.routers.bscws.entrypoints=websecure
      - traefik.http.routers.bscws.rule=Host(`${WS_HOST}.${DOMAIN}`)
      - traefik.http.routers.bscws.tls.certresolver=letsencrypt
      - traefik.http.routers.bscwslb.service=bscws
      - traefik.http.routers.bscwslb.entrypoints=websecure
      - traefik.http.routers.bscwslb.rule=Host(`${WS_LB}.${DOMAIN}`)
      - traefik.http.routers.bscwslb.tls.certresolver=letsencrypt
      - traefik.http.services.bscws.loadbalancer.server.port=${WS_PORT}
      - metrics_scrape=true
      - metrics_path=/debug/metrics/prometheus
      - metrics_port=6060

  set-prune-marker:
    profiles: ["tools"]
    image: alpine:3
    user: "10001:10001"
    restart: "no"
    volumes:
      - geth-data:/home/bsc/data
    entrypoint: ["/bin/sh","-c"]
    command: /bin/sh

volumes:
  geth-data:
